name: teste
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: hello-world
      run: echo "hello world!"
    - name: goodbye-world
      run: echo "goodbye world!"
